"""Shared validation testing helpers."""
from workflows.shared.helpers.validation_payloads import (
    SQLI_AUTH_PAYLOADS,
    SQLI_NUMERIC_PAYLOADS,
    XSS_REFLECTED_PAYLOADS,
    WEAK_PASSWORDS,
    INVALID_EMAILS,
    DISALLOWED_FILE_EXTENSIONS,
    ALLOWED_DOCUMENT_EXTENSIONS,
)

__all__ = [
    "SQLI_AUTH_PAYLOADS",
    "SQLI_NUMERIC_PAYLOADS",
    "XSS_REFLECTED_PAYLOADS",
    "WEAK_PASSWORDS",
    "INVALID_EMAILS",
    "DISALLOWED_FILE_EXTENSIONS",
    "ALLOWED_DOCUMENT_EXTENSIONS",
]
